name: update-packages
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell --command ./scripts/update-dependencies.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-token: ${{ secrets.DLDT_BOT_PAT }}
          author: "dldt bot <203830002+dldt-bot@users.noreply.github.com>"
          push-to-fork: dldt-bot/anari-nix
          base: "main"
          labels: "dependencies"
          draft: true
          delete-branch: true
          sign-commits: true
          title: "Update dependencies"
          body: "This PR updates the flake.lock file."
          branch: "update-flake-lock"
