name: update-packages
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 2 * * 0" # runs weekly on Sunday at 02:00
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell --command ./scripts/update-packages-version.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: dldt-bot
      - uses: peter-evans/create-pull-request@v7
        id: create-pull-request
        with:
          branch-token: ${{ steps.generate-token.outputs.token }}
          token: ${{ secrets.DLDT_BOT_PAT }}
          push-to-fork: dldt-bot/anari-nix
          base: "main"
          labels: "packages-version"
          delete-branch: true
          sign-commits: true
          title: "Update packages to latest version"
          body: "This PR updates packages to latest version."
          branch: "update-packages"
          commit-message: "Update packages to latest version"
      - name: Enable Pull Request Automerge
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        run: |
          gh pr merge ${{ steps.create-pull-request.outputs.pull-request-number }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.DLDT_BOT_PAT }}
